version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16 # Postgres 16 with pgvector pre-installed
    container_name: grabpic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: grabpic_user
      POSTGRES_PASSWORD: grabpic_pass
      POSTGRES_DB: grabpic_db
    ports:
      - "5432:5432" # your machine port : container port
    volumes:
      - postgres_data:/var/lib/postgresql/data # persists data between restarts

  redis:
    image: redis:7-alpine
    container_name: grabpic_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
